const { runAI } = require("./brain");
const { writeFiles } = require("./utils/writer");
const { execSync } = require("child_process");
const fs = require("fs");
const { logBuild } = require("./utils/logger");
const { fullScan } = require("./utils/analyzer");

function classifyFile(file) {
  if (file.includes(".github/workflows")) return "GitHub Actions Workflow";
  if (file.includes("src/agent")) return "Core Agent System";
  if (file.includes("Temporary Builder")) return "Builder System";
  if (file.includes("docs")) return "Documentation";
  return "System File";
}

function explain(file) {
  const type = classifyFile(file.path);

  let notes = "";

  if (file.path.includes("workflow")) {
    notes = "Automates CI/CD pipeline execution.";
  } else if (file.path.includes("brain")) {
    notes = "AI reasoning + generation engine.";
  } else if (file.path.includes("runner")) {
    notes = "Executes AI-generated outputs and commits to GitHub.";
  } else if (file.path.includes("logger")) {
    notes = "Stores execution history of AI builds.";
  } else {
    notes = "Core system component.";
  }

  let credentials = "None detected";

  if (file.path.includes("docker") || file.path.includes("hf") || file.path.includes("deploy")) {
    credentials = "May require GitHub Secrets or environment variables (.env / Actions Secrets)";
  }

  return { type, notes, credentials };
}

(async () => {
  console.log("🚀 Running Temporary Builder...");

  const result = await runAI();

  if (!result) {
    console.log("❌ AI failed");
    return;
  }

  writeFiles(result.files);

  fs.writeFileSync(
    "Temporary Builder/docs/raw.txt",
    JSON.stringify(result, null, 2)
  );

  const scanned = fullScan();

  const detailed = scanned.map(f => {
    const info = explain(f);

    return `
### 📄 ${f.path}

- Type: ${info.type}
- Size: ${f.size} chars
- Empty: ${f.empty ? "⚠️ YES" : "NO"}
- Purpose: ${info.notes}
- Credentials: ${info.credentials}
`;
  }).join("\n");

  const summary = `
# 🧠 AI FULL BUILD REPORT (AUTOGENERATED)

## 📦 GENERATED FILES
${result.files?.map(f => "- " + f.path).join("\n") || "none"}

---

## 🔍 FULL REPOSITORY ANALYSIS

${detailed}

---

## 🧠 SYSTEM MAP

- convo.md → GitHub Actions logic
- convo2.md → Telegram AI system
- Temporary Builder → Autonomous generator engine

---

## ⚙️ STATUS
FULL SYSTEM SCAN COMPLETE

## ⚠️ NOTES
- Check missing credentials in GitHub Secrets
- Verify workflows are enabled in Actions tab
- Ensure no duplicate workflows are active
`;

  fs.writeFileSync("Temporary Builder/docs/results.md", summary);

  logBuild(result);

  execSync("git config user.name 'AI-BOT'");
  execSync("git config user.email 'ai@bot.local'");

  execSync("git add .");

  const changed = execSync("git status --porcelain").toString();
  if (!changed) return;

  execSync("git commit -m '🧠 AI FULL SYSTEM ANALYSIS UPDATE' || true");
  execSync("git pull --rebase origin main || true");
  execSync("git push origin main || true");

  console.log("✅ Full system analysis completed");
})();
