const { runAI } = require("./brain");
const { writeFiles } = require("./utils/writer");
const { execSync } = require("child_process");
const fs = require("fs");
const { logBuild } = require("./utils/logger");

(async () => {
  console.log("🚀 Running Temporary Builder...");

  const result = await runAI();

  if (!result) {
    console.log("❌ AI failed");
    return;
  }

  // INSTALL
  if (result.install?.length) {
    execSync("npm install " + result.install.join(" "), { stdio: "inherit" });
  }

  // WRITE GENERATED FILES (ROOT AI-REMOTE)
  writeFiles(result.files);

  // SAVE RAW AI OUTPUT
  fs.writeFileSync(
    "Temporary Builder/docs/raw.txt",
    JSON.stringify(result, null, 2)
  );

  // BUILD SUMMARY (HUMAN READABLE)
  const summary = `
# AI BUILD RESULTS

## 📦 Files Generated:
${result.files?.map(f => "- " + f.path).join("\n") || "none"}

## 📌 Dependencies:
${(result.install || []).join(", ")}

## 🧠 Source Systems:
- convo.md → GitHub Actions logic
- convo2.md → Telegram AI logic

## ⚙️ Status:
AUTO-GENERATED BY TEMPORARY BUILDER
`;

  fs.writeFileSync("Temporary Builder/docs/results.md", summary);

  // SAVE HISTORY (IMPORTANT FIX)
  logBuild(result);

  // GIT SAFE SYNC
  execSync("git config user.name 'AI-BOT'");
  execSync("git config user.email 'ai@bot.local'");

  execSync("git add .");

  const changed = execSync("git status --porcelain").toString();

  if (!changed) {
    console.log("No changes.");
    return;
  }

  execSync("git commit -m '🤖 AI Temporary Builder Update' || true");
  execSync("git pull --rebase origin main || true");
  execSync("git push origin main || true");

  console.log("✅ Build complete + logged");
})();
