name: Release Notes
on: [push]
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate release notes
        run: echo 'Generating release notes...'