name: Versioning
on: [push]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version bump
        run: echo 'Bumping version...'