const fs = require("fs");
const { hash } = require("./analyzer");

const INDEX_PATH = "Temporary Builder/memory/repo-index.json";

function load() {
  return JSON.parse(fs.readFileSync(INDEX_PATH, "utf-8"));
}

function save(index) {
  fs.writeFileSync(INDEX_PATH, JSON.stringify(index, null, 2));
}

function writeFiles(files = []) {
  const index = load();

  for (const f of files) {
    const h = hash(f.content);

    // WHY FILE EXISTS (reasoning layer)
    if (!index.reasons[f.path]) {
      index.reasons[f.path] = "Generated by AI system from convo analysis";
    }

    // dependency graph (basic inference)
    index.dependencies[f.path] = (f.content.match(/require\(["'](.*?)["']\)/g) || []);

    if (index.files[f.path] === h) {
      console.log("⏭ skip (no change):", f.path);
      continue;
    }

    const dir = f.path.split("/").slice(0, -1).join("/");
    if (dir) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(f.path, f.content);
    console.log("✔ wrote:", f.path);

    index.files[f.path] = h;
  }

  index.lastBuild = new Date().toISOString();
  save(index);
}

module.exports = { writeFiles };
