name: Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate release notes
        run: npm run release-notes