# Tagging Workflow
name: Tagging

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Tag
        run: |
          git tag v$(cat docs/VERSION.md | grep 'VERSION:' | cut -d ' ' -f2)
          git push origin --tags