name: Tagging

on:
  push:
    branches:
      - main

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create tag
        run: git tag v$(node -p "require('./package.json').version") && git push --tags